Local JAR Support
diffplug/blowdryer pull request #20
Opened 2021-05-27 01:51 UTC by chris-serra

Fixes #12 

**If you only changed documentation or typos, you can ignore the following.**

After creating the PR, please update the [CHANGELOG.md](https://github.com/diffplug/blowdryer/blob/master/CHANGELOG.md).  We follow [keep a changelog conventions](https://keepachangelog.com/en/1.0.0/), everything you need to know is below:

```
## [Unreleased]
### Added (or Changed, Deprecated, Removed, Fixed, Security)
- Bullet point for your change ([#1](https://link-to-your-pr))

### Changed (add a header for your entry as necessary)
```

**We won't look at your PR until you update the changelog**.  We can always the change the changelog before merging, but it's easier for us to review if you have already condensed the scope of your changes into the changelog.

2021-05-27 02:16 UTC, chris-serra commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +		String allSafeCharacters = url.replaceAll("[^a-zA-Z0-9-+_.]", "-");
Redundant `\\`. `.` doesn't need to be escaped in a character class.

2021-05-28 04:22 UTC, nedtwigg requested changes
Implementation looks sound! Some housekeeping before I can merge :)

2021-05-28 04:22 UTC, nedtwigg commented on CHANGELOG.md
> +## [1.1.2] - 2021-05-26
Remove the 1.1.2 line, it should be

```
## [Unreleased]
### Added
- blah
```

Our release process parses the changelog and makes release notes from the Unreleased section ([spotless-changelog](https://github.com/diffplug/spotless-changelog)).

This will also fix all the premature version bumps in the docs which add noise to the PR diff.

2021-05-28 04:22 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +		if (url != null && url.startsWith("file:///")) {
don't need the nullcheck

2021-05-28 04:22 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +		String allSafeCharacters = url.replaceAll("[^a-zA-Z0-9-+_.]", "-");
Cool, thanks!

2021-05-28 04:22 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/BlowdryerSetup.java
> +	public void localJar(String jarFilePath) {
I think this should be `File jarFile`. The usage would be:

```gradle
blowdryerSetup {
  localJar(file('path/to/file.jar'))
}
```

The reason is that I think someday someone will want to merge something like this:

```gradle
blowdryerSetup {
  mavenJar('com.acme:buildscripts:1.2')
}
```

And it will be very tempting to think: Maybe `maven` means "read from server", and `localJar` means "cache this locally"? So I can just use the same string?

```gradle
blowdryerSetup {
  localJar('com.acme:buildscripts:1.2')
}
```

Making the argument a `File` makes it clear that `localJar` really does mean pass a literal concrete File.

2021-05-28 07:20 UTC, chris-serra commented
@nedtwigg Would you like me to update the README's "How to use"?

Also, the `repoSubFolder` isn't used for the Local JAR, as `src/main/resources` folder structure is not included in a built JAR file (from what I've seen).

2021-05-28 15:10 UTC, nedtwigg commented
Yes please on both counts!

2021-05-28 23:14 UTC, merged

2021-05-28 23:58 UTC, nedtwigg commented
I'm working on publishing the newest version. Feel free to submit a new PR with doc improvements at your leisure.

2021-05-30 18:36 UTC, nedtwigg commented
Published in `1.2.0`

2021-05-30 22:55 UTC, chris-serra commented
@nedtwigg Updated README in #22