Add support for Bitbucket Cloud and Server
diffplug/blowdryer pull request #23
Opened 2021-06-21 20:40 UTC by bHacklv

- `filenameSafe` now removes query parameters and appends file name to the end of the link to preserve its original file extension.
- Support for Bitbucket Cloud and Server ([#20](add-link-to-PR)).

2021-06-21 23:47 UTC, nedtwigg requested changes
Thanks, this is a great PR! It has one big problem which is that it adds a new `GitAnchorType BRANCH`. I think that's a bad idea, but I'm happy to merge it anyway.

But! We should merge Bitbucket support without `BRANCH` support. Then, after that has been merged, I'd be happy to take a new PR which adds `BRANCH` support. I just created a new issue for mutable branch support in #24.

If you delete support for `BRANCH`, it will be quick and easy to get this merged. From there, it's also easy to close out #24 if you still want to.

2021-06-21 23:47 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/BlowdryerSetup.java
> +		private final String anchor;
As an aside, yes these are currently effectively final, but it would be fine to add modifier methods like `repoOrg(String repoOrg)` in which case they could no longer be final (see #24).

2021-06-22 07:33 UTC, bHacklv commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +				BITBUCKET_COMMIT_HASH_CACHE.clear();
It is still nice to have for TAG type.
I will explain more in detail what happens there.

Bitbucket Cloud for some reason doesn't have the support of personal access tokens, which can be used to authenticate requests to private repos via HTTPs, like so:
```
// TAG: test/2/b
// this works as this repo is public
https://bitbucket.org/bHack/blowdryer/raw/test/2/b/src/main/resources/sample
```

Instead, only for **Bitbucket Cloud private repos**, we have to use this Bitbucket [API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/src/%7Bcommit%7D/%7Bpath%7D)

And as you can see it only supports retrieving RAW files via commit hash.
So, for TAG type configurations, we have to retrieve the commit hash of a tag using this Bitbucket [API](https://developer.atlassian.com/bitbucket/api/2/reference/resource/repositories/%7Bworkspace%7D/%7Brepo_slug%7D/refs/tags/%7Bname%7D#get), and then use the hash in the previous request.

So if someone decides to use this configuration:

```gradle
bitbucket('acme/blowdryer-acme', 'tag', 'v1.4.5').cloudAuth("username:appPassword")
```
without the caching, we will do N request for tag commit hash (where N = .file/.prop/etc retieval configurations).

What would you suggest doing? :)

2021-06-22 08:18 UTC, bHacklv commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +		if (url.contains("?at")) {
You are right that this is only for Bitbucket, but can be extended if required.

I saw that For GitLab the end of the URLs also will be an anchor.
```
String urlEnd = "/raw?ref=" + encodeUrlPart(anchor);
```

With Bitbucket, and without the above change, I get this exception:
```
// branch as anchor
Caused by: java.lang.IllegalArgumentException: The file name extension 'xml-at-refs-heads-master' is not part of the supported file extensions [[LINE_ORIENTED, XML]].

// commit as anchor
Caused by: java.lang.IllegalArgumentException: The file name extension 'com-proje--5l72Kw--2ba2fc1bb88a667a09fb4db3e9a6262d2acb9fad' is not part of the supported file extensions [[LINE_ORIENTED, XML]].
```

It could be only the case for .xml files.
In my project, I reference a cfg repo with spotless.
spotless.gradle has this line:
```
 eclipse().configFile 干.file("checkstyle/style.xml")
```

2021-06-22 08:29 UTC, bHacklv commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +				BITBUCKET_COMMIT_HASH_CACHE.clear();
Never mind, you are right!
After rewriting the original anchor and retrieved hash (and the type) - no need for the cache.

2021-06-23 17:32 UTC, nedtwigg commented
I made a few tweaks:

- instead of `cloudAuth` and `serverAuth`, users can just do `auth` and we can deal with it ourselves
- using a custom domain implies `server()`, so we don't need to specify that ourselves
- I made https://bitbucket.org/diffplug/blowdryer

If you're okay with these changes, I'm ready to merge and release.

2021-06-23 17:58 UTC, bHacklv commented
> I made a few tweaks:
> 
> * instead of `cloudAuth` and `serverAuth`, users can just do `auth` and we can deal with it ourselves
> * using a custom domain implies `server()`, so we don't need to specify that ourselves
> * I made https://bitbucket.org/diffplug/blowdryer
> 
> If you're okay with these changes, I'm ready to merge and release.

lgtm!

2021-06-23 18:28 UTC, merged

2021-06-23 18:40 UTC, nedtwigg commented
Released in `1.3.0`

2021-06-23 19:19 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +		if (url.contains("?at")) {
Preserving file extensions is a good idea, I proposed a less fragile way to do that in #25.