Add retry on (gitlab) rateLimit
diffplug/blowdryer pull request #30
Opened 2022-05-11 15:51 UTC by vgropp

we ran into the gitlab rate limit in some CI jobs and i tried a first solution to retry after the given delay

what do you think @nedtwigg , any comments?
There is no stop condition yet, so it might retry forever, maybe we need some counter but i did not come up with a solution

2022-05-11 16:01 UTC, nedtwigg commented
Retry functionality is a great idea! Happy to merge this in some form. Not good to retry forever though, definitely needs some kind of max retry counter.

2022-05-11 19:38 UTC, nedtwigg requested changes
I'm all for supporting retries, but I think this approach is too flexible, no need for plugins IMO.

2022-05-11 19:38 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +			Blowdryer.rateLimitPlugin = rateLimitPlugin;
Instead of `rateLimitPlugin`, maybe Blowdryer just has `RETRY_MS = 100` and `RETRY_MAX_ATTEMPTS = 100` and if either of them is `<=0` then no retry takes place? I don't think we need the same configurability for this as `ResourcePlugin` and `AuthPlugin`.

2022-05-12 06:55 UTC, vgropp commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +			Blowdryer.rateLimitPlugin = rateLimitPlugin;
Well, i think this is very gitlab specific, at least the response code 429, github seems to use 403 according to https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting, thats why i used  plugin to not check for gitlab (and maybe github for another implementation) in downloadRemote. If you are fine with alwas retry on response code 429, i can remove the plugin and always add the interceptor.

2022-05-13 10:26 UTC, vgropp commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +			Blowdryer.rateLimitPlugin = rateLimitPlugin;
based on your Suggestion i removed the Plugin and apply the Interceptor by default, assuming github (status 403) and bitbucked (couldnt find any information) will not send 429

2022-05-13 18:54 UTC, nedtwigg requested changes
Thanks, looks much better! I think it's okay if we end up with interwoven rate-limiting logic for the various gitlab/github/etc backends.

2022-05-13 18:54 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/BlowdryerSetup.java
> +
I think this is unused and can be removed.

2022-05-13 18:54 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/RateLimitInterceptor.java
> +	private static long RETRX_MAX_MS = 300_000;
Wow, 5 minutes is pretty long, but I guess it's better than a failure. If my build configuration was hanging for minutes, or even seconds, I think I would want to know why. Maybe:

```
System.out.println("Blowdryer request to " + chain.request().url() + " has been rate-limited, retrying in " + BLAH + " seconds.")
```

2022-05-13 18:54 UTC, nedtwigg commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +	}
I don't understand why this needed to get added, but if I'll take your word for it if it's necessary.

2022-05-16 10:25 UTC, vgropp commented on src/main/java/com/diffplug/blowdryer/BlowdryerSetup.java
> +
done

2022-05-16 10:26 UTC, vgropp commented on src/main/java/com/diffplug/blowdryer/RateLimitInterceptor.java
> +	private static long RETRX_MAX_MS = 300_000;
yes, you are right, i lowered it 90 seconds which should be way enough for gitlab, and added the output

2022-05-16 10:29 UTC, vgropp commented on src/main/java/com/diffplug/blowdryer/Blowdryer.java
> +	}
i used a different approach in the test for a temp dir (TemporaryFolder Rule), instead of the StandardSystemProperty. In that case the Preconditions in initTempDir failes. I change and removed it, but still think the tests are not really independent as all Tests need to use the same Tempdir.

2022-05-20 06:48 UTC, vgropp commented
@nedtwigg what do you think about my last changes, i could rebase and sqash the commits maybe if you wish

2022-05-20 08:15 UTC, nedtwigg commented
Sorry for delay - no squash needed, I'll get this merged and released tomorrow.

2022-05-20 23:31 UTC, merged

2022-05-20 23:58 UTC, nedtwigg commented
Published in `1.6.0`. Great PR, sorry for the slow merge :)